language: node_js
node_js:
  - '8.7.0'
cache:
  directories:
    - node_modules

script:
  - npm run coverage

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    branch: master
